Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  #config.vm.synced_folder "./", "/vagrant", create: true
  #config.vm.provision "shell", path: "./provision/setup.sh"
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true

  config.vm.provider "virtualbox" do |v|
    v.name = "Host-Machine"
    v.memory = 2048
    v.cpus = 4
  end

  # Point to provisioning script.
  config.vm.provision "shell", path: "./provision/setup.sh"

  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  config.vm.provision "shell", inline:
     "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"

end
